apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-service-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - match:
    - uri:
        prefix: /api/products
    rewrite:
      uri: /products
    route:
    - destination:
        host: {{ .Values.productService.host }}
        port:
          number: {{ .Values.productService.port }}
  - match:
    - uri:
        prefix: /api/product
    rewrite:
      uri: /product
    route:
    - destination:
        host: {{ .Values.productService.host }}
        port:
          number: {{ .Values.productService.port }}
  - match:
    - uri:
        regex: /api/product/(\d+)
    rewrite:
      uri: /product/{match[1]}
    route:
    - destination:
        host: {{ .Values.productService.host }}
        port:
          number: {{ .Values.productService.port }}
