apiVersion: v1
kind: Service
metadata:
  name: "{{ include "product-service.fullname" . }}"
spec:
  selector:
    app: "{{ include "product-service.name" . }}"
  ports:
    - name: "{{ .Values.service.name }}"
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8001
