apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: default
data:
  DB_HOST: cloudnative2.czeoksqka75q.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: cloudnative
