replicaCount: 2

image:
  repository: ashrafelshazlii/order-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: http-order
  type: ClusterIP
  port: 8002

resources: {}

env:
  DB_HOST: localhost
  DB_PORT: 5432
  DB_NAME: cloudnative
  DB_USER: user
  DB_PASSWORD: password
