apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "frontend-service.name" . }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "frontend-service.name" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "frontend-service.name" . }}"
        version: v1
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
