apiVersion: v1
kind: Service
metadata:
  name:  "{{ include "frontend-service.name" . }}"
spec:
  selector:
    app:  "{{ include "frontend-service.name" . }}"
  ports:
    - name:  "{{ .Values.service.name }}"
      protocol: TCP
      port:  {{ .Values.service.port }}
      targetPort: 80
